-- Seed Cars
INSERT INTO public.cars (id, name, category, passengers, luggage, ac, image, description, features) VALUES
('toyota-rumion', 'Toyota Rumion', 'Family MPV', 6, '3 bags', true, '/images/toyota-rumion.png', 'A practical and comfortable family MPV ideal for local city rides, station pickups, and airport transfers.', ARRAY['Spacious cabin', 'Family-friendly', 'Smooth city ride', 'Rear AC vents']),
('toyota-innova-crysta', 'Toyota Innova Crysta', 'Premium MPV', 7, '4 bags', true, '/images/toyota-innova-crysta.jpg', 'A premium MPV known for comfort and stability, perfect for outstation trips and long family travel.', ARRAY['Premium comfort', 'Long-route ready', 'Ample luggage', 'Ideal for groups']),
('maruti-swift-dzire', 'Maruti Swift Dzire', 'Economy Sedan', 4, '2 bags', true, '/images/maruti-swift-dzire.jpg', 'An economical and reliable sedan for local rides, corporate transfers, and budget-friendly travel.', ARRAY['Economy segment', 'Fuel efficient', 'Comfortable seating', 'Perfect for couples']),
('maruti-ertiga', 'Maruti Ertiga', 'Family MPV', 6, '3 bags', true, '/images/maruti-ertiga.jpg', 'A balanced MPV for medium-size families with comfortable seating and practical luggage space.', ARRAY['Comfort + value', 'Easy access seating', 'City and highway', 'Family favorite']),
('force-urbania-luxury', 'Force Urbania Luxury (17 Seater)', 'Luxury Van', 17, '10 bags', true, '/images/force-urbania.jpg', 'A luxury 17-seater ideal for large groups, events, corporate outings, and extended tour circuits.', ARRAY['17 seater', 'Group comfort', 'Tour-ready layout', 'High roof cabin']),
('mahindra-scorpio', 'Mahindra Scorpio', 'Premium SUV', 6, '4 bags', true, '/images/mahindra-scorpio.jpg', 'A robust premium SUV suitable for mixed road conditions and comfortable family adventures.', ARRAY['SUV stance', 'Road presence', 'Comfortable travel', 'Strong performance']),
('toyota-fortuner', 'Toyota Fortuner', 'Premium SUV', 6, '5 bags', true, '/images/toyota-fortuner.jpg', 'A top-end premium SUV for executive travel, family tours, and high-comfort long routes.', ARRAY['Executive class', 'Premium interiors', 'Extra luggage', 'Luxury ride']),
('toyota-innova-crysta-premium', 'Toyota Innova Crysta (Premium)', 'Premium MPV', 7, '4 bags', true, '/images/toyota-innova-crysta-premium.jpg', 'A premium configuration of Innova Crysta for travelers who prefer extra comfort and refinement.', ARRAY['Premium segment', '7 passengers', 'Comfort seats', 'Tour optimized'])
ON CONFLICT (id) DO NOTHING;

-- Seed Places
INSERT INTO public.places (title, image, description) VALUES
('White Rann', '/placeimges/WhiteRann.png', 'The Great Rann of Kutch is a salt marsh in the Thar Desert in the Kutch District of Gujarat, India. It is one of the largest salt deserts in the world, known for its surreal white landscapes, especially under the full moon.'),
('Mandvi Beach', '/placeimges/MandviBeach.png', 'Mandvi Beach is a serene and beautiful beach known for its golden sands, calm waters, and historic shipbuilding yards. It offers a perfect escape with opportunities for camel rides and water sports.'),
('Bhuj Heritage', '/placeimges/BhujHeritage.png', 'Bhuj is the historic heart of Kutch, offering rich cultural heritage with majestic palaces like Aina Mahal and Prag Mahal, along with vibrant local markets and traditional Kutchi handicrafts.'),
('Kutch Road Trips', '/placeimges/KutchRoadTrips.png', 'Experience the ultimate road trip through the barren, yet majestic landscapes of Kutch. Drive through endless horizons, discover hidden villages, and experience the raw beauty of Gujarat.'),
('Dholavira', '/placeimges/dholavira.png', 'Dholavira is an archaeological site belonging to the Indus Valley Civilization. It is one of the five largest Harappan sites and prominent archaeological sites in India belonging to the Indus Valley Civilization.'),
('Koteshwar', '/placeimges/koteshwer.png', 'Koteshwar is a small village and the location of an ancient Shiva temple. It lies at the westernmost limit of India, overlooking the Arabian Sea, offering spectacular sunset views.'),
('Swaminarayan Temple Bhuj', '/placeimges/swaminrayntemplebhuj.png', 'The Shri Swaminarayan Mandir in Bhuj is an architectural masterpiece constructed entirely of marble and teak wood. It is a spectacular spiritual center known for its pristine beauty and intricate carvings.'),
('Mata no Madh', '/placeimges/matanomadh.png', 'Mata no Madh is a village in the Lakhpat Taluka of Kutch district, famous for the temple dedicated to Ashapura Mata, the patron deity of the former Jadeja rulers of Cutch State.'),
('Aina Mahal', '/placeimges/ainamahal.png', 'Aina Mahal, or the Palace of Mirrors, is an 18th-century palace in Bhuj. Known for its stunning European-influenced architecture and exquisite mirrored interiors, it remains a magnificent symbol of Kutchi royal heritage.'),
('Vijay Vilas Palace', '/placeimges/vijayvilas.png', 'The grand Vijay Vilas Palace in Mandvi is a breathtaking summer retreat built with red sandstone. Featuring majestic Rajput architecture, intricate stone carvings, and lush gardens, it''s a testament to the opulence of the Kutch royalty.');
